# Generated by Django 5.0.3 on 2024-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dsecriptions',
            new_name='descriptions',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Title',
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.FileField(blank=True, default=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='technology',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
