# Generated by Django 5.0.3 on 2024-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_rename_dsecriptions_data_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='descriptions',
            field=models.TextField(max_length=250),
        ),
    ]
