# Generated by Django 5.0.3 on 2024-03-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_alter_data_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
