# Generated by Django 5.0.3 on 2024-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_alter_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
