# Generated by Django 5.0.3 on 2024-03-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_remove_project_password_remove_project_password2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(default=-1.0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(default=-1.0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(default=-1.0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.EmailField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='first_name',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='last_name',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='phone',
            field=models.CharField(default=-1.0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(default=-1.0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_code',
            field=models.CharField(default=-1.0, max_length=25),
            preserve_default=False,
        ),
    ]
